### ISSUE TITLE
will sometimes suffering the "Out of memory" exception when accessing symbols from SymbolServer

### ISSUE THREAD

**Issue by ali50m** [Beckhoff/TF6000_ADS_DOTNET_V4_Samples#5]
I`m running some unit tests with Ads nuget v4. Sometimes, I will encounter an Ads issue which said below. It has a small chance of happening, but after happening it will be no longer able to read the Symbols in SymbolServer. It just happens after running unit tests many times but without clear clues. I have to restart the CX2020 to continue.

Could you let me know how this OOM issue happen, or how to debug it?  Or maybe how to recover from the OOM issue? Many thanks!

xunit log: 
```
TwinCAT.Ads.AdsErrorException: Ads-Error 0x70A : Out of memory.

TwinCAT.Ads.AdsErrorException
Ads-Error 0x70A : Out of memory.
   at TwinCAT.Ads.Internal.TcAdsDllWrapper.ThrowOnError(AdsErrorCode adsErrorCode)
   at TwinCAT.Ads.TypeSystem.AdsSymbolLoader.loadTypes(TimeSpan timeout)
   at TwinCAT.Ads.TypeSystem.AdsSymbolLoader.loadData()
   at TwinCAT.Ads.TypeSystem.AdsSymbolLoader.get_Symbols()
   at TwinCAT.Ads.TypeSystem.AdsSymbolServer.get_Symbols()
   at AdsApiTests.TwinCatAds4Tests.GetSymbols_FromAdsServer_ShouldWork() in C:\Users\Liu\source\repos\AdsBigData\test\AdsApiTests\TwinCatAds4Tests.cs:line 325
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

code.

```csharp
[Fact]
public void GetSymbols_FromAdsServer_ShouldWork()
{
    using var session = new AdsSession(new AmsNetId(_netId), Port);
    
    var connection = session.Connect() as IAdsConnection;
 
    Assert.NotNull(connection);

    var symbols = session.SymbolServer.Symbols;   // OOM exception happens here!
    Assert.NotNull(symbols);
}
```

Environment:

- dotnet sdk version: 6.0.401
- nuget: Beckhoff.TwinCAT.Ads v 4.4.21
- dev machine: Win10 64bit, TwinCAT 2.11 x64 Engineering v2.11.2307.0
- target device: CX2020, TwinCAT 2.11.2307

**Comment by MichaelKno** [comment]
Hi ali50m,

this error is not coming from the client side. The target PC seems to run out of memory.

As this is not an error in the ADS client, I will close this issue here. Please reach out to our support department (support@beckhoff.com) for further investigations.

Best regards
